### ISSUE TITLE
It is not working while trying to open it.

### ISSUE THREAD

**Issue by sakonachhoeurng** [catdad/unofficial-hipchat#15]
You can see the screenshot of this error  @catdad 
![screenshot from 2016-08-10 07 47 26](https://cloud.githubusercontent.com/assets/12217854/17538384/f7b317aa-5ece-11e6-8e78-b189af2e57e7.png)

**Comment by catdad** [comment]
Did you check any of the options suggested on the screen? Can you tell me what happens when you checked those things?

**Comment by sakonachhoeurng** [comment]
Hi,
when I click on "close this loader" that are going to work with hipchat.
For this case I just wonder why it shows this message have as in the screenshot.
