### ISSUE TITLE
Support for standalone server

### ISSUE THREAD

**Issue by fusion94** [catdad/unofficial-hipchat#17]
Many teams have purchased the standalone version. Would be nice to be able to enter a URL field instead of having it default to the cloud version every time.

**Comment by catdad** [comment]
This is already supported. Click on the 3 bar hambuger-like button in the top right. It will save it and default to that URL until the next time you change it.

**Comment by fusion94** [comment]
wasn't intuitive but I got it to work, might want to add as helper to ensure that people know to enter in Protocol+URL; i.e. https://foo.bar.com as opposed to foo.bar.com.

**Comment by catdad** [comment]
Sorry, I don't use this app much, and Google is deprecating packaged apps very soon so I don't plan on investing time in this, but as far as I remember, the input field already has a sample URL visible which displays the https://www.hipchat.com/chat, protocol and all.
