### ISSUE TITLE
hipchat is crashing

### ISSUE THREAD

**Issue by damonoutlaw12** [catdad/unofficial-hipchat#21]
Whenever I attempt to log into Hipchat the app flickers and will not allow my to selected the correct captcha. If goes back and forth and I am unable to use the app or sign in

**Comment by catdad** [comment]
Thanks for the report.

Unfortunately, this is a Chrome packaged app, and Chrome no longer supports packaged apps. In fact, developers can no longer publish them. Further, HipChat is also going away.

As such, this app is no longer maintained. Sorry about that.
