### ISSUE TITLE
Enabling desktop notification is not saved after relaunch

### ISSUE THREAD

**Issue by jfretin** [catdad/unofficial-hipchat#3]
I enabled desktop notifications, but the choice doesn't seem to be saved, as the app asks me again at next launch.

version  1.0.15259.39

![espace de travail 1_025](https://cloud.githubusercontent.com/assets/120841/10014440/851e7350-6119-11e5-980f-8f38e9708030.jpg)

**Comment by catdad** [comment]
@jfretin This is tied to your preference on the HipChat web client. Did you clear your browser settings or run the app in incognito mode?

**Comment by jfretin** [comment]
Oh yes, I didn't connect in normal chrome at all. I just did and it correctly saved the notifications preference!

Thanks! I didn't think of this.

By the way, great app you did here. I'm currently stuck with the ugly linux hipchat client...
